### ISSUE TITLE
Requirements.txt file

### ISSUE THREAD

**Issue by ghost** [ZeroMe1a/NHentai_Sampler#1]
Colque um arquivo "requirements.txt" para um usuário leigo conseguir instalar as bibliotecas necessárias (com um simples comando pip install -r requirements.txt), assim usuários que não sabem instalar as bibliotecas sozinhos podem rodar esse comando e instalar todas as bibliotecas (API's, o que for) facilmente.

**Comment by ZeroMe1a** [comment]
Opa, valeu pelo feedback e pela ideia, já vou atualizar o github

_Maurinho <notifications@github.com> escreveu no dia domingo, 15/11/2020
à(s) 09:12:
